---
title: "Mapa economia criativa Porto Alegre"
output:
    flexdashboard::flex_dashboard:
      theme: bootstrap
---

```{r setup, include=FALSE}


library(haven)
library(ggmap)
library(rgeos)
library(flexdashboard)
library(data.table)
library(dplyr)
library(tidyr)
library(leaflet)
library(rgdal)
library(tibble)
library(htmlwidgets)
library(htmltools)

setwd("C:\\Users\\gustavod.santos\\Documents\\R\\mapas")

POA <- read.csv("C:\\Users\\gustavod.santos\\Documents\\R\\mapas\\POA_ESTAB_2019.csv", sep = ";")
POA <- POA%>%
  filter(Ind.Atividade.Ano == 1)

neighborhoods <- readOGR("C:\\Users\\gustavod.santos\\Documents\\R\\mapas\\shapefile_POA", "Bairros_2016", encoding = "UTF-8")
neighborhoods <- spTransform(neighborhoods, CRS("+proj=longlat +datum=WGS84"))
neighborhoods$NOME <- factor(c("LAMI", "BOA VISTA DO SUL", "EXTREMA", "BELÉM NOVO", "SÃO CAETANO", "PONTA GROSSA", "CHAPÉU DO SOL", "LAGEADO", "SERRARIA", "GUARUJÁ", "ABERTA DOS MORROS", "ESPÍRITO SANTO", "HÍPICA", "PITINGA", "CAMPO NOVO", "IPANEMA",  "JARDIM ISABEL",  "PEDRA REDONDA", "RESTINGA",  "VILA CONCEIÇÃO", "SÉTIMO CÉU", "TRISTEZA", "CAMAQUÃ", "VILA NOVA", "BELÉM VELHO", "VILA ASSUNÇÃO", "CAVALHADA", "CASCATA",  "NONOAI", "CRISTAL", "TERESÓPOLIS", "GLÓRIA", "ARQUIPÉLAGO", "CORONEL APARÍCIO BORGES", "VILA JOÃO PESSOA", "VILA SÃO JOSÉ", "SANTA TEREZA", "MEDIANEIRA", "AGRONOMIA", "SANTO ANTÔNIO", "JARDIM BOTÂNICO", "JARDIM DO SALSO", "MENINO DEUS", "JARDIM CARVALHO", "AZENHA", "BOM JESUS", "SANTA CECÍLIA", "SANTANA", "PRAIA DE BELAS", "CIDADE BAIXA", "FARROUPILHA", "BOM FIM", "MORRO SANTANA", "PETRÓPOLIS", "RIO BRANCO", "CHÁCARA DAS PEDRAS", "TRÊS FIGUEIRAS", "BELA VISTA", "JARDIM SABARÁ", "VILA JARDIM", "INDEPENDÊNCIA", "MONTSERRAT", "CENTRO HISTÓRICO", "JARDIM EUROPA", "MÁRIO QUINTANA", "BOA VISTA", "MOINHOS DE VENTO", "AUXILIADORA", "JARDIM LEOPOLDINA", "PASSO DAS PEDRAS", "HIGIENÓPOLIS", "FLORESTA", "VILA IPIRANGA", "JARDIM ITU", "PASSO DA AREIA", "CRISTO REDENTOR", "SANTA MARIA GORETTI", "SÃO GERALDO", "PARQUE SANTA FÉ", "COSTA E SILVA", "RUBEM BERTA", "JARDIM LINDÓIA", "SÃO SEBASTIÃO", "JARDIM SÃO PEDRO", "JARDIM FLORESTA", "SÃO JOÃO", "NAVEGANTES", "SANTA ROSA DE LIMA", "FARRAPOS", "HUMAITÁ", "ANCHIETA", "SARANDI", "LOMBA DO PINHEIRO", "PARTENON"))

POA$endereco <- paste("CEP", POA$CEP.Estab, "- PORTO ALEGRE")

coord2 <- fread("C:\\Users\\gustavod.santos\\Documents\\R\\mapas\\enderecos_coord.csv")

secoes_coord_spatial <- coord2 %>%
  select(lon, lat) %>%
  SpatialPoints(CRS("+proj=longlat +datum=WGS84"))


bairros <- over(secoes_coord_spatial, neighborhoods)

bairros2 <- cbind(bairros, coord2)


base_coord = merge(bairros2, POA, by="endereco")


base_coord$GrupoCNAE[is.na(base_coord$GrupoCNAE)] <- 99

base_coord$D_Grupo_11 <- ifelse(base_coord$Grupo == "11", 1, 0) 
base_coord$D_Grupo_12 <- ifelse(base_coord$Grupo == "12", 1, 0) 
base_coord$D_Grupo_21 <- ifelse(base_coord$Grupo == "21", 1, 0) 
base_coord$D_Grupo_22 <- ifelse(base_coord$Grupo == "22", 1, 0) 
base_coord$D_Grupo_31 <- ifelse(base_coord$Grupo == "31", 1, 0) 
base_coord$D_Grupo_32 <- ifelse(base_coord$Grupo == "32", 1, 0) 
base_coord$D_Grupo_41 <- ifelse(base_coord$Grupo == "41", 1, 0) 
base_coord$D_Grupo_42 <- ifelse(base_coord$Grupo == "42", 1, 0)

base_coord2 <- base_coord%>%
  group_by(endereco, CEP.Estab)%>%
  summarise(Grupo_11 = sum(D_Grupo_11), Grupo_12 = sum(D_Grupo_12), Grupo_21 = sum(D_Grupo_21), Grupo_22 = sum(D_Grupo_22),
            Grupo_31 = sum(D_Grupo_31), Grupo_32 = sum(D_Grupo_32), Grupo_41 = sum(D_Grupo_41), Grupo_42 = sum(D_Grupo_42), lat = mean(lat), lon = mean(lon))

base_coord2$Total <- rowSums(base_coord2[,c(3,4,5,6,7,8,9,10)])

tag.map.title <- tags$style(HTML("
  .leaflet-control.map-title { 
    transform: translate(-50%,20%);
    position: fixed !important;
    left: 50%;
    text-align: center;
    padding-left: 10px; 
    padding-right: 10px; 
    background: rgba(255,255,255,0.75);
    font-weight: bold;
    font-size: 20px;
  }
"))

title <- tags$div(
  tag.map.title, HTML("1º colocado em cada bairro")
)  

pal9 <- colorBin(palette = "YlOrRd", bins = 9,  domain = base_coord2$Total)
base_coord2 <- base_coord2%>%
  filter(Total > 0)

base_coord2 <- base_coord2%>%
  filter(CEP.Estab != 99999999)

base_coord2$radius = 1+(base_coord2$Total)*0.4

```
Mapa Porto Alegre
=====================================

```{r}

leaflet(data=base_coord2)%>%
  addProviderTiles("CartoDB")%>%
  setView(lng = -51.22786, lat =  -30.02859, zoom = 15)%>%
  addPolygons(data = neighborhoods, weight = 1.5, color = "grey", fillOpacity = 0)%>%
  addCircles(base_coord2$lon, base_coord2$lat, radius = ~base_coord2$Total*5, weight = 1, fillOpacity = 0.2,
              popup =~paste("<B>CEP:</B>",CEP.Estab,
                            "</br>","Total:", format(round(as.numeric(Total)), nsmall=0, big.mark="."),
                            "<br>","Patrimônio e Culturas Tradicionais:", format(round(as.numeric(base_coord2$Grupo_11)), nsmall=0, big.mark="."),
                            "<br>", "Artes Visuais e Performáticas:", format(round(as.numeric(base_coord2$Grupo_12)), nsmall=0, big.mark="."),
                            "<br>", "Publicação, editoração e mídia:", format(round(as.numeric(base_coord2$Grupo_21)), nsmall=0, big.mark="."),
                            "<br>", "Audiovisual:", format(round(as.numeric(base_coord2$Grupo_22)), nsmall=0, big.mark="."),
                            "<br>", "Arquitetura, Design e Moda:", format(round(as.numeric(base_coord2$Grupo_31)), nsmall=0, big.mark="."),
                            "<br>", "Publicidade e pesquisa de mercado:", format(round(as.numeric(base_coord2$Grupo_32)), nsmall=0, big.mark="."),
                            "<br>", "Ensino e pesquisa:", format(round(as.numeric(base_coord2$Grupo_41)), nsmall=0, big.mark="."),
                            "<br>", "TI e software, pesquisa e desenvolvimento:", format(round(as.numeric(base_coord2$Grupo_42)), nsmall=0, big.mark="."), sep="\n"))%>%
 htmlwidgets::onRender("function(el, x) { 
  L.control.zoom({ position: 'topright' }).addTo(this)
  }")


```


Ficha Técnica
=====================================

**FICHA TÉCNICA**

Os mapas mostram a distribuição espacial dos estabelecimentos criativos por subgrupos a partir de dados da RAIS.

Elaborado por Gustavo Diefenbach dos Santos  
E-mail: gustavod.santos@portoalegre.rs.gov.br


